name: Lambda Dev

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: developmentseed/titiler
          path: titiler
      
      - run: |
          ls -al
          ls -al titiler
      
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: Install CDK
        run: npm install -g aws-cdk
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: pip install
        run: |
          cd titiler && pip install -e .["deploy"]
          pip install aws-cdk.aws_apigatewayv2_integrations

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'titiler-lambda-dev'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
